In [ ]:
import numpy as np

In [ ]:
#Array Creation
project=np.array([[1,2,3,4],[41,42,43,44],[99,98,97,96]])
project

array([[ 1,  2,  3,  4],
       [41, 42, 43, 44],
       [99, 98, 97, 96]])

In [ ]:
#Data Exploration
project.shape
project.size
project.ndim

2

In [ ]:
#Data Transformation
project.T

array([[ 1, 41, 99],
       [ 2, 42, 98],
       [ 3, 43, 97],
       [ 4, 44, 96]])

In [ ]:
#Adding a new column in an existing array
newcol = np.array([[5], [45], [100]])
res = np.hstack((project,newcol))
print(res)

[[  1   2   3   4   5]
 [ 41  42  43  44  45]
 [ 99  98  97  96 100]]


In [ ]:
#Updation
project[2][1]=100
print(project)

[[  1   2   3   4]
 [ 41  42  43  44]
 [ 99 100  97  96]]


In [ ]:
#Deletion
delt=np.delete(project,1)
print(delt)

[  1   3   4  41  42  43  44  99 100  97  96]


In [ ]:
#Datatype Handling
project[0][2]=47.4
print(project)

[[  1   2  47   4]
 [ 41  42  47  44]
 [ 99 100  47  96]]


In [ ]:
#Copy of an arrayc
pro=np.copy(project)
print(pro)

[[  1   2  47   4]
 [ 41  42  47  44]
 [ 99 100  47  96]]


In [ ]:
#View of an same array
pro.view()
print(pro)

[[  1   2  47   4]
 [ 41  42  47  44]
 [ 99 100  47  96]]
